/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.webservicescheck.services.countryinfoservice1.controller;

import com.webservicescheck.services.countryinfoservice1.services.CountryInfoService1Service;
import com.webservicescheck.services.countryinfoservice1.CapitalCity;
import java.lang.String;
import com.webservicescheck.services.countryinfoservice1.CapitalCityResponse;
import com.webservicescheck.services.countryinfoservice1.CountriesUsingCurrency;
import com.webservicescheck.services.countryinfoservice1.CountriesUsingCurrencyResponse;
import com.webservicescheck.services.countryinfoservice1.CountryCurrency;
import com.webservicescheck.services.countryinfoservice1.CountryCurrencyResponse;
import com.webservicescheck.services.countryinfoservice1.CountryFlag;
import com.webservicescheck.services.countryinfoservice1.CountryFlagResponse;
import com.webservicescheck.services.countryinfoservice1.CountryISOCode;
import com.webservicescheck.services.countryinfoservice1.CountryISOCodeResponse;
import com.webservicescheck.services.countryinfoservice1.CountryIntPhoneCode;
import com.webservicescheck.services.countryinfoservice1.CountryIntPhoneCodeResponse;
import com.webservicescheck.services.countryinfoservice1.CountryName;
import com.webservicescheck.services.countryinfoservice1.CountryNameResponse;
import com.webservicescheck.services.countryinfoservice1.CurrencyName;
import com.webservicescheck.services.countryinfoservice1.CurrencyNameResponse;
import com.webservicescheck.services.countryinfoservice1.FullCountryInfo;
import com.webservicescheck.services.countryinfoservice1.FullCountryInfoResponse;
import com.webservicescheck.services.countryinfoservice1.FullCountryInfoAllCountries;
import com.webservicescheck.services.countryinfoservice1.FullCountryInfoAllCountriesResponse;
import com.webservicescheck.services.countryinfoservice1.LanguageISOCode;
import com.webservicescheck.services.countryinfoservice1.LanguageISOCodeResponse;
import com.webservicescheck.services.countryinfoservice1.LanguageName;
import com.webservicescheck.services.countryinfoservice1.LanguageNameResponse;
import com.webservicescheck.services.countryinfoservice1.ListOfContinentsByCode;
import com.webservicescheck.services.countryinfoservice1.ListOfContinentsByCodeResponse;
import com.webservicescheck.services.countryinfoservice1.ListOfContinentsByName;
import com.webservicescheck.services.countryinfoservice1.ListOfContinentsByNameResponse;
import com.webservicescheck.services.countryinfoservice1.ListOfCountryNamesByCode;
import com.webservicescheck.services.countryinfoservice1.ListOfCountryNamesByCodeResponse;
import com.webservicescheck.services.countryinfoservice1.ListOfCountryNamesByName;
import com.webservicescheck.services.countryinfoservice1.ListOfCountryNamesByNameResponse;
import com.webservicescheck.services.countryinfoservice1.ListOfCountryNamesGroupedByContinent;
import com.webservicescheck.services.countryinfoservice1.ListOfCountryNamesGroupedByContinentResponse;
import com.webservicescheck.services.countryinfoservice1.ListOfCurrenciesByCode;
import com.webservicescheck.services.countryinfoservice1.ListOfCurrenciesByCodeResponse;
import com.webservicescheck.services.countryinfoservice1.ListOfCurrenciesByName;
import com.webservicescheck.services.countryinfoservice1.ListOfCurrenciesByNameResponse;
import com.webservicescheck.services.countryinfoservice1.ListOfLanguagesByCode;
import com.webservicescheck.services.countryinfoservice1.ListOfLanguagesByCodeResponse;
import com.webservicescheck.services.countryinfoservice1.ListOfLanguagesByName;
import com.webservicescheck.services.countryinfoservice1.ListOfLanguagesByNameResponse;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;

@RestController
@RequestMapping(value = "/countryInfo1")
public class CountryInfoService1Controller {

    @Autowired
    private CountryInfoService1Service countryInfoService1Service;

    @RequestMapping(value = "/capitalCity", method = RequestMethod.GET)
    public CapitalCityResponse capitalCity(@RequestParam(value = "SCountryISOCode", required = false) String SCountryISOCode) {
        CapitalCity parameters = new CapitalCity();
        parameters.setSCountryISOCode(SCountryISOCode);
        return countryInfoService1Service.capitalCity(parameters);
    }

    @RequestMapping(value = "/countriesUsingCurrency", method = RequestMethod.GET)
    public CountriesUsingCurrencyResponse countriesUsingCurrency(@RequestParam(value = "SISOCurrencyCode", required = false) String SISOCurrencyCode) {
        CountriesUsingCurrency parameters = new CountriesUsingCurrency();
        parameters.setSISOCurrencyCode(SISOCurrencyCode);
        return countryInfoService1Service.countriesUsingCurrency(parameters);
    }

    @RequestMapping(value = "/countryCurrency", method = RequestMethod.GET)
    public CountryCurrencyResponse countryCurrency(@RequestParam(value = "SCountryISOCode", required = false) String SCountryISOCode) {
        CountryCurrency parameters = new CountryCurrency();
        parameters.setSCountryISOCode(SCountryISOCode);
        return countryInfoService1Service.countryCurrency(parameters);
    }

    @RequestMapping(value = "/countryFlag", method = RequestMethod.GET)
    public CountryFlagResponse countryFlag(@RequestParam(value = "SCountryISOCode", required = false) String SCountryISOCode) {
        CountryFlag parameters = new CountryFlag();
        parameters.setSCountryISOCode(SCountryISOCode);
        return countryInfoService1Service.countryFlag(parameters);
    }

    @RequestMapping(value = "/countryISOCode", method = RequestMethod.GET)
    public CountryISOCodeResponse countryISOCode(@RequestParam(value = "SCountryName", required = false) String SCountryName) {
        CountryISOCode parameters = new CountryISOCode();
        parameters.setSCountryName(SCountryName);
        return countryInfoService1Service.countryISOCode(parameters);
    }

    @RequestMapping(value = "/countryIntPhoneCode", method = RequestMethod.GET)
    public CountryIntPhoneCodeResponse countryIntPhoneCode(@RequestParam(value = "SCountryISOCode", required = false) String SCountryISOCode) {
        CountryIntPhoneCode parameters = new CountryIntPhoneCode();
        parameters.setSCountryISOCode(SCountryISOCode);
        return countryInfoService1Service.countryIntPhoneCode(parameters);
    }

    @RequestMapping(value = "/countryName", method = RequestMethod.GET)
    public CountryNameResponse countryName(@RequestParam(value = "SCountryISOCode", required = false) String SCountryISOCode) {
        CountryName parameters = new CountryName();
        parameters.setSCountryISOCode(SCountryISOCode);
        return countryInfoService1Service.countryName(parameters);
    }

    @RequestMapping(value = "/currencyName", method = RequestMethod.GET)
    public CurrencyNameResponse currencyName(@RequestParam(value = "SCurrencyISOCode", required = false) String SCurrencyISOCode) {
        CurrencyName parameters = new CurrencyName();
        parameters.setSCurrencyISOCode(SCurrencyISOCode);
        return countryInfoService1Service.currencyName(parameters);
    }

    @RequestMapping(value = "/fullCountryInfo", method = RequestMethod.GET)
    public FullCountryInfoResponse fullCountryInfo(@RequestParam(value = "SCountryISOCode", required = false) String SCountryISOCode) {
        FullCountryInfo parameters = new FullCountryInfo();
        parameters.setSCountryISOCode(SCountryISOCode);
        return countryInfoService1Service.fullCountryInfo(parameters);
    }

    @RequestMapping(value = "/fullCountryInfoAllCountries", method = RequestMethod.GET)
    public FullCountryInfoAllCountriesResponse fullCountryInfoAllCountries() {
        FullCountryInfoAllCountries parameters = new FullCountryInfoAllCountries();
        return countryInfoService1Service.fullCountryInfoAllCountries(parameters);
    }

    @RequestMapping(value = "/languageISOCode", method = RequestMethod.GET)
    public LanguageISOCodeResponse languageISOCode(@RequestParam(value = "SLanguageName", required = false) String SLanguageName) {
        LanguageISOCode parameters = new LanguageISOCode();
        parameters.setSLanguageName(SLanguageName);
        return countryInfoService1Service.languageISOCode(parameters);
    }

    @RequestMapping(value = "/languageName", method = RequestMethod.GET)
    public LanguageNameResponse languageName(@RequestParam(value = "SISOCode", required = false) String SISOCode) {
        LanguageName parameters = new LanguageName();
        parameters.setSISOCode(SISOCode);
        return countryInfoService1Service.languageName(parameters);
    }

    @RequestMapping(value = "/ofContinentsByCode", method = RequestMethod.GET)
    public ListOfContinentsByCodeResponse listOfContinentsByCode() {
        ListOfContinentsByCode parameters = new ListOfContinentsByCode();
        return countryInfoService1Service.listOfContinentsByCode(parameters);
    }

    @RequestMapping(value = "/ofContinentsByName", method = RequestMethod.GET)
    public ListOfContinentsByNameResponse listOfContinentsByName() {
        ListOfContinentsByName parameters = new ListOfContinentsByName();
        return countryInfoService1Service.listOfContinentsByName(parameters);
    }

    @RequestMapping(value = "/ofCountryNamesByCode", method = RequestMethod.GET)
    public ListOfCountryNamesByCodeResponse listOfCountryNamesByCode() {
        ListOfCountryNamesByCode parameters = new ListOfCountryNamesByCode();
        return countryInfoService1Service.listOfCountryNamesByCode(parameters);
    }

    @RequestMapping(value = "/ofCountryNamesByName", method = RequestMethod.GET)
    public ListOfCountryNamesByNameResponse listOfCountryNamesByName() {
        ListOfCountryNamesByName parameters = new ListOfCountryNamesByName();
        return countryInfoService1Service.listOfCountryNamesByName(parameters);
    }

    @RequestMapping(value = "/ofCountryNamesGroupedByContinent", method = RequestMethod.GET)
    public ListOfCountryNamesGroupedByContinentResponse listOfCountryNamesGroupedByContinent() {
        ListOfCountryNamesGroupedByContinent parameters = new ListOfCountryNamesGroupedByContinent();
        return countryInfoService1Service.listOfCountryNamesGroupedByContinent(parameters);
    }

    @RequestMapping(value = "/ofCurrenciesByCode", method = RequestMethod.GET)
    public ListOfCurrenciesByCodeResponse listOfCurrenciesByCode() {
        ListOfCurrenciesByCode parameters = new ListOfCurrenciesByCode();
        return countryInfoService1Service.listOfCurrenciesByCode(parameters);
    }

    @RequestMapping(value = "/ofCurrenciesByName", method = RequestMethod.GET)
    public ListOfCurrenciesByNameResponse listOfCurrenciesByName() {
        ListOfCurrenciesByName parameters = new ListOfCurrenciesByName();
        return countryInfoService1Service.listOfCurrenciesByName(parameters);
    }

    @RequestMapping(value = "/ofLanguagesByCode", method = RequestMethod.GET)
    public ListOfLanguagesByCodeResponse listOfLanguagesByCode() {
        ListOfLanguagesByCode parameters = new ListOfLanguagesByCode();
        return countryInfoService1Service.listOfLanguagesByCode(parameters);
    }

    @RequestMapping(value = "/ofLanguagesByName", method = RequestMethod.GET)
    public ListOfLanguagesByNameResponse listOfLanguagesByName() {
        ListOfLanguagesByName parameters = new ListOfLanguagesByName();
        return countryInfoService1Service.listOfLanguagesByName(parameters);
    }
}
