/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

package com.webservicescheck.services.calc.services;
import com.webservicescheck.services.calc.*;
import java.util.List;

import com.wavemaker.runtime.soap.util.SoapSettingsResolver;
import com.wavemaker.runtime.soap.SoapServiceSettings;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import javax.xml.ws.BindingProvider;



@Service
public class CalcService{

    @Autowired
    @Qualifier("calcSoapServiceSettings")
    private SoapServiceSettings soapServiceSettings;


	public AddResponse add(  com.webservicescheck.services.calc.Add parameters )
	          {
 	    Calculator calculator = new Calculator();
 CalculatorSoap calculatorsoap = calculator.getCalculatorSoap();
 SoapSettingsResolver.setBindingProperties((BindingProvider)calculatorsoap, soapServiceSettings);
 return calculatorsoap.add(parameters );
	}

	public DivideResponse divide(  com.webservicescheck.services.calc.Divide parameters )
	          {
 	    Calculator calculator = new Calculator();
 CalculatorSoap calculatorsoap = calculator.getCalculatorSoap();
 SoapSettingsResolver.setBindingProperties((BindingProvider)calculatorsoap, soapServiceSettings);
 return calculatorsoap.divide(parameters );
	}

	public MultiplyResponse multiply(  com.webservicescheck.services.calc.Multiply parameters )
	          {
 	    Calculator calculator = new Calculator();
 CalculatorSoap calculatorsoap = calculator.getCalculatorSoap();
 SoapSettingsResolver.setBindingProperties((BindingProvider)calculatorsoap, soapServiceSettings);
 return calculatorsoap.multiply(parameters );
	}

	public SubtractResponse subtract(  com.webservicescheck.services.calc.Subtract parameters )
	          {
 	    Calculator calculator = new Calculator();
 CalculatorSoap calculatorsoap = calculator.getCalculatorSoap();
 SoapSettingsResolver.setBindingProperties((BindingProvider)calculatorsoap, soapServiceSettings);
 return calculatorsoap.subtract(parameters );
	}
}
